### ISSUE TITLE
Failed 0.2.0 release

### ISSUE THREAD

**Issue by jtpio** [martinRenou/jupyterlab-day#8]
Trying to release 0.2.0 failed with the following:

![image](https://github.com/user-attachments/assets/ebeef260-73a6-430a-8436-7b7819fceba2)

Will try to re-run the workflow later today to see if the issue fixes itself.

**Comment by jtpio** [comment]
Ah it was because the trusted publisher was not yet set up.

All good now: https://github.com/jupyterlab-contrib/jupyterlab-day/releases/tag/v0.2.0

**Comment by martinRenou** [comment]
Thanks!
